# Reducing angular derivative
gains:
  #pos: {x: 8.5, y: 8.5, z: 15.0}   # z can be 17
  #vel: {x: 3.0, y: 3.0, z: 3.5}    # z can be 5
  pos: {x: 3.7, y: 3.7, z: 8.0} 
  vel: {x: 2.4, y: 2.4, z: 3.0}  
  rot: {x: 1.5, y: 1.5, z: 0.12}
# ang: {x: 0.4, y: 0.4, z: 0.025}
# rot: {x: 1.6, y: 1.6, z: 0.12}
  ang: {x: 0.13, y: 0.13, z: 0.012}
  ki:  {x: 0.0, y: 0.0, z: 0.0}
#Aggressive
#gains:
#  pos: {x: 5.0, y: 5.0, z: 8.0}
#  vel: {x: 3.2, y: 3.2, z: 3.0}
#  rot: {x: 1.3, y: 1.3, z: 0.25}
#  ang: {x: 0.25, y: 0.25, z: 0.025}
#  ki:  {x: 0.0, y: 0.0, z: 0.0}
##Original:
#gains:
#  pos: {x: 3.7, y: 3.7, z: 5.2}
#  vel: {x: 2.4, y: 2.4, z: 3}
#  rot: {x: 1.3, y: 1.3, z: 0.3}
#  ang: {x: 0.25, y: 0.25, z: 0.03}
#  ki:  {x: 0.0, y: 0.0, z: 0.0}
corrections:
  kf: -0.000000003 
  r: 0.0
  p: 0.0

